### ISSUE TITLE
I want to get the Chinese name of the item, how should I change it?

### ISSUE THREAD

**Issue by adink1** [azerothcore/mod-random-enchants#19]
I want to get the Chinese name of the item, how should I change it?
I am using the Chinese client. I want to get the item name in Chinese, not the current English name. How should I modify it?

**Comment by Helias** [comment]
it's weird that you get it in english, may you have the server DBC files in english and the client ones in chinese? check the server side DBC

**Comment by adink1** [comment]
I don't think it is a problem with the server DBC file, because I use other modules to display normal (mod-transmog), I think it should be the problem of item name acquisition.

**Comment by pangolp** [comment]
In my case I am using the client in Spanish, and I also always get the name of the item in English. Although I have to admit that I have the server DBCs in English, not Spanish, because I downloaded them from the repository https://github.com/wowgaming/client-data/releases/. In the pull request that I am putting together, I modified the code so that it displays it in the client's language. At least now I see it in Spanish, you should see it in Chinese.
