### ISSUE TITLE
open Vanilla item crash

### ISSUE THREAD

**Issue by w5860363** [azerothcore/mod-random-enchants#23]
1. `.additem 21513` or `.additem 8484`
- https://www.wowhead.com/item=21513/ahnqiraj-war-effort-supplies
- https://www.wowhead.com/item=8484/gadgetzan-water-co-care-package (open item)

## Crash
[aea540181b38+_worldserver.exe_[20-10_21-45-24].txt](https://github.com/azerothcore/mod-random-enchants/files/13055726/aea540181b38%2B_worldserver.exe_.20-10_21-45-24.txt)

**Comment by pangolp** [comment]
- I am testing the items, with the new changes that I am uploading in the pull request, and no crash is generated now, possibly because the SQL query was wrong. However, in the case of the item https://www.wowhead.com/item=8484/gadgetzan-water-co-care-package, when it is opened, it apparently does not have any items inside, or it has a very low probability, because I opened several, and never received any.

- In the case of https://www.wowhead.com/item=21513/ahnqiraj-war-effort-supplies, I sometimes received an item, resulting in 3 random enchantments, sometimes 1, and sometimes nothing. I don't know if the module has to grant an enchantment or it may not generate one.
