### ISSUE TITLE
if player in  a team,random enchantment not work

### ISSUE THREAD

**Issue by catontheway** [azerothcore/mod-random-enchants#5]
If the player is in a team state, the random enchantment of the equipment does not work

**Comment by pangolp** [comment]
Hello, if you're so kind, I'm going to ask you to create another issue, but I was like, provide more information, because with what you mention here, I can't understand the problem. Therefore, I can't solve it or try to solve it. Keep in mind that the module was recently updated, so first, perform the tests using the latest version of it. If the error continues, I await your report. Greetings.
